@forlang
[{{ locale }}]
ListWindowTitle = "{{ strings.heading_title_transaction_details }}"
DetailsWindowTitle = "{{ strings.heading_transaction_details }}"
CreatedAt = "{{ strings.panel_transaction_date }}"
OrderNumber = "{{ strings.panel_order_number }}"
PaymentUniqueId = "{{ strings.payment_number }}"
Type = "{{ strings.response_type }}"
TransactionId = "{{ strings.panel_transcation_id }}"
ParentTransactionId = "{{ strings.panel_parent_transaction_id }}"
ProviderTransactionId = "{{ strings.panel_provider_transaction_id }}"
ProviderTransactionReference = "{{ strings.ptrid }}"
TransactionType = "{{ strings.panel_action }}"
TransactionState = "{{ strings.panel_transaction_state }}"
PaymentMethod = "{{ strings.panel_payment_method }}"
Amount = "{{ strings.panel_amount }}"
Currency = "{{ strings.panel_currency }}"
Response = "{{ strings.text_response_data }}"
RequestId = "{{ strings.requestId }}"
Request = "{{ strings.text_request_data }}"
OpenTransactionTooltip = "{{ strings.open_transaction_details }}"
OpenOrderTooltip = "{{ strings.open_order_details }}"
NoOrderNumber = "{{ strings.note_no_order }}"
OrderCanceled = "{{ strings.note_canceled }}"

@endforlang
